# Generated by Django 3.1.5 on 2021-01-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='guest',
            new_name='equipment',
        ),
    ]
